version: "3.9"
services:
  app:
    build: ./app
    container_name: garantias_app_v3_4_git
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./app/uploads:/app/uploads
    restart: always
