name: CI - Build Docker Compose

on:
  push:
    branches:
      - main
      - version_test
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instalar Docker Engine usando acci√≥n oficial
      - name: Set up Docker
        uses: docker/setup-docker@v3

      # Instalar Docker Compose plugin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Validar docker funcional
      - name: Test Docker
        run: docker --version

      - name: Test Docker Compose
        run: docker compose version || echo "compose plugin activo"

      - name: Build docker images
        run: |
          docker compose build

      - name: Run containers for validation
        run: |
          docker compose up -d
          sleep 10
          docker compose ps

      - name: Shut down containers
        run: docker compose down
