name: CI - Docker Compose Build

on:
  push:
    branches:
      - main
      - version_test

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Solo para verificar que docker está instalado
      - name: Validate Docker installation
        run: |
          docker --version
          docker compose version

      # Construir imágenes
      - name: Build Docker images
        run: docker compose build

      # Levantar contenedores para validar
      - name: Run containers
        run: |
          docker compose up -d
          sleep 5
          docker compose ps

      # Apagar contenedores
      - name: Stop containers
        run: docker compose down

